$(document).ready(function() {
	
	$('body').on('change', 'input', function() {
	
		if ($('#result').is(':hidden')) {
			$('#result').show();
		}
	
		var w = $('input#width').val();
		var c = $('input#columns').val();
		var m = $('input#margin').val();
	
		if (w === '') {
			w = $('input#width').attr('placeholder');
		} else {
			w = parseInt(w);
		}
	
		if (c === '') {
			c = $('input#columns').attr('placeholder');
		} else {
			c = parseInt(c);
		}
	
		if (m === '') {
			m = $('input#margin').attr('placeholder');
		} else {
			m = parseInt(m);
		}
		
		$('#result').html('\\*\n');
		$('#result').append('* Skeleton V1.2\n');
		$('#result').append('* Copyright 2011, Dave Gamache\n');
		$('#result').append('* www.getskeleton.com\n');
		$('#result').append('* Free to use under the MIT license.\n');
		$('#result').append('* http://www.opensource.org/licenses/mit-license.php\n');
		$('#result').append('* 6/20/2012\n');
		$('#result').append('*/\n');
		$('#result').append(' \n');
		$('#result').append(' \n');
		$('#result').append('/* Table of Contents\n');
		$('#result').append('==================================================\n');
		$('#result').append('    #Base ' + w + ' Grid\n');
		$('#result').append('    #Base 960 Grid\n');
		$('#result').append('    #Tablet (Portrait)\n');
		$('#result').append('    #Mobile (Portrait)\n');
		$('#result').append('    #Mobile (Landscape)\n');
		$('#result').append('    #Clearing */\n');
		$('#result').append(' \n');
		$('#result').append(' \n');
		$('#result').append(' \n');
		$('#result').append('/* #Base ' + w + ' Grid\n');
		$('#result').append('================================================== */\n');
		$('#result').append(' \n');
		$('#result').append('    .container                                  { position: relative; width: ' + w + 'px; margin: 0 auto; padding: 0; }\n');
		$('#result').append('    .container .column,\n');
		$('#result').append('    .container .columns                         { float: left; display: inline; margin-left: ' + m + 'px; margin-right: ' + m + 'px; }\n');
		$('#result').append('    .row                                        { margin-bottom: 20px; }\n');
		$('#result').append(' \n');
		$('#result').append('    /* Nested Column Classes */\n');
		$('#result').append('    .column.alpha, .columns.alpha               { margin-left: 0; }\n');
		$('#result').append('    .column.omega, .columns.omega               { margin-right: 0; }\n');
		$('#result').append(' \n');
		$('#result').append('    /* Base Grid */\n');
		$('#result').append('    .container .one.column,\n');
		$('#result').append('    .container .one.columns                     { width: ' + (w / c * 1 - m) + 'px;  }\n');
		$('#result').append('    .container .two.columns                     { width: ' + (w / c * 2 - m) + 'px; }\n');
		$('#result').append('    .container .three.columns                   { width: ' + (w / c * 3 - m) + 'px; }\n');
		$('#result').append('    .container .four.columns                    { width: ' + (w / c * 4 - m) + 'px; }\n');
		$('#result').append('    .container .five.columns                    { width: ' + (w / c * 5 - m) + 'px; }\n');
		$('#result').append('    .container .six.columns                     { width: ' + (w / c * 6 - m) + 'px; }\n');
		$('#result').append('    .container .seven.columns                   { width: ' + (w / c * 7 - m) + 'px; }\n');
		$('#result').append('    .container .eight.columns                   { width: ' + (w / c * 8 - m) + 'px; }\n');
		$('#result').append('    .container .nine.columns                    { width: ' + (w / c * 9 - m) + 'px; }\n');
		$('#result').append('    .container .ten.columns                     { width: ' + (w / c * 10 - m) + 'px; }\n');
		$('#result').append('    .container .eleven.columns                  { width: ' + (w / c * 11 - m) + 'px; }\n');
		$('#result').append('    .container .twelve.columns                  { width: ' + (w / c * 12 - m) + 'px; }\n');
		$('#result').append('    .container .thirteen.columns                { width: ' + (w / c * 13 - m) + 'px; }\n');
		$('#result').append('    .container .fourteen.columns                { width: ' + (w / c * 14 - m) + 'px; }\n');
		$('#result').append('    .container .fifteen.columns                 { width: ' + (w / c * 15 - m) + 'px; }\n');
		$('#result').append('    .container .sixteen.columns                 { width: ' + (w / c * 16 - m) + 'px; }\n');
		$('#result').append(' \n');
		$('#result').append('    .container .one-third.column                { width: ' + ((w - m) / 3) + 'px; }\n');
		$('#result').append('    .container .two-thirds.column               { width: ' + ((w - m) / 3 * 2) + 'px; }\n');
		$('#result').append(' \n');
		$('#result').append('    /* Offsets */\n');
		$('#result').append('    .container .offset-by-one                   { padding-left: ' + (w / c * 1) + 'px;  }\n');
		$('#result').append('    .container .offset-by-two                   { padding-left: ' + (w / c * 2) + 'px; }\n');
		$('#result').append('    .container .offset-by-three                 { padding-left: ' + (w / c * 3) + 'px; }\n');
		$('#result').append('    .container .offset-by-four                  { padding-left: ' + (w / c * 4) + 'px; }\n');
		$('#result').append('    .container .offset-by-five                  { padding-left: ' + (w / c * 5) + 'px; }\n');
		$('#result').append('    .container .offset-by-six                   { padding-left: ' + (w / c * 6) + 'px; }\n');
		$('#result').append('    .container .offset-by-seven                 { padding-left: ' + (w / c * 7) + 'px; }\n');
		$('#result').append('    .container .offset-by-eight                 { padding-left: ' + (w / c * 8) + 'px; }\n');
		$('#result').append('    .container .offset-by-nine                  { padding-left: ' + (w / c * 9) + 'px; }\n');
		$('#result').append('    .container .offset-by-ten                   { padding-left: ' + (w / c * 10) + 'px; }\n');
		$('#result').append('    .container .offset-by-eleven                { padding-left: ' + (w / c * 11) + 'px; }\n');
		$('#result').append('    .container .offset-by-twelve                { padding-left: ' + (w / c * 12) + 'px; }\n');
		$('#result').append('    .container .offset-by-thirteen              { padding-left: ' + (w / c * 13) + 'px; }\n');
		$('#result').append('    .container .offset-by-fourteen              { padding-left: ' + (w / c * 14) + 'px; }\n');
		$('#result').append('    .container .offset-by-fifteen               { padding-left: ' + (w / c * 15) + 'px; }\n');
		$('#result').append(' \n');
		$('#result').append(' \n');
		$('#result').append(' \n');
		$('#result').append('/* #Base 960 Grid\n');
		$('#result').append('================================================== */\n');
		$('#result').append(' \n');
		$('#result').append('    .container                                  { position: relative; width: 960px; margin: 0 auto; padding: 0; }\n');
		$('#result').append('    .container .column,\n');
		$('#result').append('    .container .columns                         { float: left; display: inline; margin-left: 10px; margin-right: 10px; }\n');
		$('#result').append('    .row                                        { margin-bottom: 20px; }\n');
		$('#result').append(' \n');
		$('#result').append('    /* Nested Column Classes */\n');
		$('#result').append('    .column.alpha, .columns.alpha               { margin-left: 0; }\n');
		$('#result').append('    .column.omega, .columns.omega               { margin-right: 0; }\n');
		$('#result').append(' \n');
		$('#result').append('    /* Base Grid */\n');
		$('#result').append('    .container .one.column,\n');
		$('#result').append('    .container .one.columns                     { width: 40px;  }\n');
		$('#result').append('    .container .two.columns                     { width: 100px; }\n');
		$('#result').append('    .container .three.columns                   { width: 160px; }\n');
		$('#result').append('    .container .four.columns                    { width: 220px; }\n');
		$('#result').append('    .container .five.columns                    { width: 280px; }\n');
		$('#result').append('    .container .six.columns                     { width: 340px; }\n');
		$('#result').append('    .container .seven.columns                   { width: 400px; }\n');
		$('#result').append('    .container .eight.columns                   { width: 460px; }\n');
		$('#result').append('    .container .nine.columns                    { width: 520px; }\n');
		$('#result').append('    .container .ten.columns                     { width: 580px; }\n');
		$('#result').append('    .container .eleven.columns                  { width: 640px; }\n');
		$('#result').append('    .container .twelve.columns                  { width: 700px; }\n');
		$('#result').append('    .container .thirteen.columns                { width: 760px; }\n');
		$('#result').append('    .container .fourteen.columns                { width: 820px; }\n');
		$('#result').append('    .container .fifteen.columns                 { width: 880px; }\n');
		$('#result').append('    .container .sixteen.columns                 { width: 940px; }\n');
		$('#result').append(' \n');
		$('#result').append('    .container .one-third.column                { width: 300px; }\n');
		$('#result').append('    .container .two-thirds.column               { width: 620px; }\n');
		$('#result').append(' \n');
		$('#result').append('    /* Offsets */\n');
		$('#result').append('    .container .offset-by-one                   { padding-left: 60px;  }\n');
		$('#result').append('    .container .offset-by-two                   { padding-left: 120px; }\n');
		$('#result').append('    .container .offset-by-three                 { padding-left: 180px; }\n');
		$('#result').append('    .container .offset-by-four                  { padding-left: 240px; }\n');
		$('#result').append('    .container .offset-by-five                  { padding-left: 300px; }\n');
		$('#result').append('    .container .offset-by-six                   { padding-left: 360px; }\n');
		$('#result').append('    .container .offset-by-seven                 { padding-left: 420px; }\n');
		$('#result').append('    .container .offset-by-eight                 { padding-left: 480px; }\n');
		$('#result').append('    .container .offset-by-nine                  { padding-left: 540px; }\n');
		$('#result').append('    .container .offset-by-ten                   { padding-left: 600px; }\n');
		$('#result').append('    .container .offset-by-eleven                { padding-left: 660px; }\n');
		$('#result').append('    .container .offset-by-twelve                { padding-left: 720px; }\n');
		$('#result').append('    .container .offset-by-thirteen              { padding-left: 780px; }\n');
		$('#result').append('    .container .offset-by-fourteen              { padding-left: 840px; }\n');
		$('#result').append('    .container .offset-by-fifteen               { padding-left: 900px; }\n');
		$('#result').append(' \n');
		$('#result').append(' \n');
		$('#result').append(' \n');
		$('#result').append('/* #Tablet (Portrait)\n');
		$('#result').append('================================================== */\n');
		$('#result').append(' \n');
		$('#result').append('    /* Note: Design for a width of 768px */\n');
		$('#result').append(' \n');
		$('#result').append('    @media only screen and (min-width: 768px) and (max-width: 959px) {\n');
		$('#result').append('        .container                                  { width: 768px; }\n');
		$('#result').append('        .container .column,\n');
		$('#result').append('        .container .columns                         { margin-left: 10px; margin-right: 10px;  }\n');
		$('#result').append('        .column.alpha, .columns.alpha               { margin-left: 0; margin-right: 10px; }\n');
		$('#result').append('        .column.omega, .columns.omega               { margin-right: 0; margin-left: 10px; }\n');
		$('#result').append('        .alpha.omega                                { margin-left: 0; margin-right: 0; }\n');
		$('#result').append(' \n');
		$('#result').append('        .container .one.column,\n');
		$('#result').append('        .container .one.columns                     { width: 28px; }\n');
		$('#result').append('        .container .two.columns                     { width: 76px; }\n');
		$('#result').append('        .container .three.columns                   { width: 124px; }\n');
		$('#result').append('        .container .four.columns                    { width: 172px; }\n');
		$('#result').append('        .container .five.columns                    { width: 220px; }\n');
		$('#result').append('        .container .six.columns                     { width: 268px; }\n');
		$('#result').append('        .container .seven.columns                   { width: 316px; }\n');
		$('#result').append('        .container .eight.columns                   { width: 364px; }\n');
		$('#result').append('        .container .nine.columns                    { width: 412px; }\n');
		$('#result').append('        .container .ten.columns                     { width: 460px; }\n');
		$('#result').append('        .container .eleven.columns                  { width: 508px; }\n');
		$('#result').append('        .container .twelve.columns                  { width: 556px; }\n');
		$('#result').append('        .container .thirteen.columns                { width: 604px; }\n');
		$('#result').append('        .container .fourteen.columns                { width: 652px; }\n');
		$('#result').append('        .container .fifteen.columns                 { width: 700px; }\n');
		$('#result').append('        .container .sixteen.columns                 { width: 748px; }\n');
		$('#result').append(' \n');
		$('#result').append('        .container .one-third.column                { width: 236px; }\n');
		$('#result').append('        .container .two-thirds.column               { width: 492px; }\n');
		$('#result').append(' \n');
		$('#result').append('        /* Offsets */\n');
		$('#result').append('        .container .offset-by-one                   { padding-left: 48px; }\n');
		$('#result').append('        .container .offset-by-two                   { padding-left: 96px; }\n');
		$('#result').append('        .container .offset-by-three                 { padding-left: 144px; }\n');
		$('#result').append('        .container .offset-by-four                  { padding-left: 192px; }\n');
		$('#result').append('        .container .offset-by-five                  { padding-left: 240px; }\n');
		$('#result').append('        .container .offset-by-six                   { padding-left: 288px; }\n');
		$('#result').append('        .container .offset-by-seven                 { padding-left: 336px; }\n');
		$('#result').append('        .container .offset-by-eight                 { padding-left: 384px; }\n');
		$('#result').append('        .container .offset-by-nine                  { padding-left: 432px; }\n');
		$('#result').append('        .container .offset-by-ten                   { padding-left: 480px; }\n');
		$('#result').append('        .container .offset-by-eleven                { padding-left: 528px; }\n');
		$('#result').append('        .container .offset-by-twelve                { padding-left: 576px; }\n');
		$('#result').append('        .container .offset-by-thirteen              { padding-left: 624px; }\n');
		$('#result').append('        .container .offset-by-fourteen              { padding-left: 672px; }\n');
		$('#result').append('        .container .offset-by-fifteen               { padding-left: 720px; }\n');
		$('#result').append('    }\n');
		$('#result').append(' \n');
		$('#result').append(' \n');
		$('#result').append('/*  #Mobile (Portrait)\n');
		$('#result').append('================================================== */\n');
		$('#result').append(' \n');
		$('#result').append('    /* Note: Design for a width of 320px */\n');
		$('#result').append(' \n');
		$('#result').append('    @media only screen and (max-width: 767px) {\n');
		$('#result').append('        .container { width: 300px; }\n');
		$('#result').append('        .container .columns,\n');
		$('#result').append('        .container .column { margin: 0; }\n');
		$('#result').append(' \n');
		$('#result').append('        .container .one.column,\n');
		$('#result').append('        .container .one.columns,\n');
		$('#result').append('        .container .two.columns,\n');
		$('#result').append('        .container .three.columns,\n');
		$('#result').append('        .container .four.columns,\n');
		$('#result').append('        .container .five.columns,\n');
		$('#result').append('        .container .six.columns,\n');
		$('#result').append('        .container .seven.columns,\n');
		$('#result').append('        .container .eight.columns,\n');
		$('#result').append('        .container .nine.columns,\n');
		$('#result').append('        .container .ten.columns,\n');
		$('#result').append('        .container .eleven.columns,\n');
		$('#result').append('        .container .twelve.columns,\n');
		$('#result').append('        .container .thirteen.columns,\n');
		$('#result').append('        .container .fourteen.columns,\n');
		$('#result').append('        .container .fifteen.columns,\n');
		$('#result').append('        .container .sixteen.columns,\n');
		$('#result').append('        .container .one-third.column,\n');
		$('#result').append('        .container .two-thirds.column  { width: 300px; }\n');
		$('#result').append(' \n');
		$('#result').append('        /* Offsets */\n');
		$('#result').append('        .container .offset-by-one,\n');
		$('#result').append('        .container .offset-by-two,\n');
		$('#result').append('        .container .offset-by-three,\n');
		$('#result').append('        .container .offset-by-four,\n');
		$('#result').append('        .container .offset-by-five,\n');
		$('#result').append('        .container .offset-by-six,\n');
		$('#result').append('        .container .offset-by-seven,\n');
		$('#result').append('        .container .offset-by-eight,\n');
		$('#result').append('        .container .offset-by-nine,\n');
		$('#result').append('        .container .offset-by-ten,\n');
		$('#result').append('        .container .offset-by-eleven,\n');
		$('#result').append('        .container .offset-by-twelve,\n');
		$('#result').append('        .container .offset-by-thirteen,\n');
		$('#result').append('        .container .offset-by-fourteen,\n');
		$('#result').append('        .container .offset-by-fifteen { padding-left: 0; }\n');
		$('#result').append(' \n');
		$('#result').append('    }\n');
		$('#result').append(' \n');
		$('#result').append(' \n');
		$('#result').append('/* #Mobile (Landscape)\n');
		$('#result').append('================================================== */\n');
		$('#result').append(' \n');
		$('#result').append('    /* Note: Design for a width of 480px */\n');
		$('#result').append(' \n');
		$('#result').append('    @media only screen and (min-width: 480px) and (max-width: 767px) {\n');
		$('#result').append('        .container { width: 420px; }\n');
		$('#result').append('        .container .columns,\n');
		$('#result').append('        .container .column { margin: 0; }\n');
		$('#result').append(' \n');
		$('#result').append('        .container .one.column,\n');
		$('#result').append('        .container .one.columns,\n');
		$('#result').append('        .container .two.columns,\n');
		$('#result').append('        .container .three.columns,\n');
		$('#result').append('        .container .four.columns,\n');
		$('#result').append('        .container .five.columns,\n');
		$('#result').append('        .container .six.columns,\n');
		$('#result').append('        .container .seven.columns,\n');
		$('#result').append('        .container .eight.columns,\n');
		$('#result').append('        .container .nine.columns,\n');
		$('#result').append('        .container .ten.columns,\n');
		$('#result').append('        .container .eleven.columns,\n');
		$('#result').append('        .container .twelve.columns,\n');
		$('#result').append('        .container .thirteen.columns,\n');
		$('#result').append('        .container .fourteen.columns,\n');
		$('#result').append('        .container .fifteen.columns,\n');
		$('#result').append('        .container .sixteen.columns,\n');
		$('#result').append('        .container .one-third.column,\n');
		$('#result').append('        .container .two-thirds.column { width: 420px; }\n');
		$('#result').append('    }\n');
		$('#result').append(' \n');
		$('#result').append(' \n');
		$('#result').append('/* #Clearing\n');
		$('#result').append('================================================== */\n');
		$('#result').append(' \n');
		$('#result').append('    /* Self Clearing Goodness */\n');
		$('#result').append('    .container:after { content: "\0020"; display: block; height: 0; clear: both; visibility: hidden; }\n');
		$('#result').append(' \n');
		$('#result').append('    /* Use clearfix class on parent to clear nested columns,\n');
		$('#result').append('    or wrap each row of columns in a <div class="row"> */\n');
		$('#result').append('    .clearfix:before,\n');
		$('#result').append('    .clearfix:after,\n');
		$('#result').append('    .row:before,\n');
		$('#result').append('    .row:after {\n');
		$('#result').append('      content: \'\0020\';\n');
		$('#result').append('      display: block;\n');
		$('#result').append('      overflow: hidden;\n');
		$('#result').append('      visibility: hidden;\n');
		$('#result').append('      width: 0;\n');
		$('#result').append('      height: 0; }\n');
		$('#result').append('    .row:after,\n');
		$('#result').append('    .clearfix:after {\n');
		$('#result').append('      clear: both; }\n');
		$('#result').append('    .row,\n');
		$('#result').append('    .clearfix {\n');
		$('#result').append('      zoom: 1; }\n');
		$('#result').append(' \n');
		$('#result').append('    /* You can also use a <br class="clear" /> to clear columns */\n');
		$('#result').append('    .clear {\n');
		$('#result').append('      clear: both;\n');
		$('#result').append('      display: block;\n');
		$('#result').append('      overflow: hidden;\n');
		$('#result').append('      visibility: hidden;\n');
		$('#result').append('      width: 0;\n');
		$('#result').append('      height: 0;\n');
		$('#result').append('    }\n');
		$('#result').append(');\n');
		$('#result').append(' \n');
		$('#result').append('	});\n');
		$('#result').append(' \n');
		
	});

});